### ISSUE TITLE
testjam doc

### ISSUE THREAD

**Issue by ayshptk** [thirdweb-dev/create-thirdweb-app#1]
## brief overview
this package lets users quickly spin up apps which use thirdweb sdks via command line. 

## installation
Clone repo using 
```
git clone https://github.com/thirdweb-dev/create-thirdweb-app
```
`cd` into `create-thirdweb-app` and run 
```
yarn install
```
build and install globally using 
```
yarn dev
```

## usage

go to any directory and run `create-thirdweb-app`, choose either one of the examples under nextjs and follow the steps

all of the above will be just ```npx create-thirdweb-app``` when published

things to test:
- [ ] it works
- [ ] chooses a project name for you if dont choose
- [ ] node modules are properly installed
- [ ] guide linked after install is easy to follow

need feedback on:
- whether procedure complicated? (shouldnt require a lot of context to understand)
- whether guide linked for the example you chose clear?
- whether the set up process could be shorter?
- bugs / errors / others

**Comment by nachoiacovino** [comment]
<img width="198" alt="image" src="https://user-images.githubusercontent.com/50103937/156264571-9c10c340-1630-4dcb-8b3b-eda98d2df604.png">
Module -> Contract
Bundle -> Edition

**Comment by joaquim-verges** [comment]
- `nextjs` is a language? I would put framework here, or something like that. Do we plan to support other frameworks?
- Should not use `module` anymore, use `contract` everywhere
- `wallet-connect` is a module?

**Comment by nkrishang** [comment]
<img width="314" alt="infinite-loading" src="https://user-images.githubusercontent.com/62195808/156265034-0d6adb44-3f3b-4568-8af8-415b97671d40.png">

Took 67s which is pretty long, and makes me think the CLI is stuck? Let's see if we can prioritize minimizing this load time (unless this is an issue specifically with my machine)

**Comment by razacodespython** [comment]
> * `nextjs` is a language? I would put framework here, or something like that. Do we plan to support other frameworks?
> 
>     * Should not use `module` anymore, use `contract` everywhere
> 
>     * `wallet-connect` is a module?

wallet connect should not be a module. 
either `hooks` or `general`

**Comment by joaquim-verges** [comment]
![Screen Shot 2022-03-01 at 3 18 43 PM](https://user-images.githubusercontent.com/3353417/156265183-343106fe-c4a2-47a4-9e13-381fab047961.png)

after running `yarn dev` in my generated app first thing i see is this

**Comment by razacodespython** [comment]
> <img alt="infinite-loading" width="314" src="https://user-images.githubusercontent.com/62195808/156265034-0d6adb44-3f3b-4568-8af8-415b97671d40.png">
> 
> Took 67s which is pretty long, and makes me think the CLI is stuck? Let's see if we can prioritize minimizing this load time (unless this is an issue specifically with my machine)

same

**Comment by joaquim-verges** [comment]
`Documentation` links to the outdated `https://thirdweb.gitbook.io/thirdweb/` - should link to portal.thirdweb.com? or maybe `typescript-sdk.thirdweb.com`

**Comment by joaquim-verges** [comment]
`examples` link is broken

**Comment by nkrishang** [comment]
<img width="250" alt="cli-deps" src="https://user-images.githubusercontent.com/62195808/156266791-8e6a9bbd-4660-4808-a3d5-271afd9043e9.png">

Everything should use `@thirdweb-dev/...` v2 dependencies
