### ISSUE TITLE
testjam doc 8th march

### ISSUE THREAD

**Issue by ayshptk** [thirdweb-dev/create-thirdweb-app#5]
## brief overview
this package lets users quickly spin up apps which use thirdweb sdks via command line. 

## installation
Clone repo using 
```
git clone https://github.com/thirdweb-dev/create-thirdweb-app
```
pull if you already had it cloned 

`cd` into `create-thirdweb-app` and run 
```
yarn install
```
build and install globally using 
```
yarn dev
```
users wont have to install it they can use npx instead

## usage

- [ ] go to any directory and run `create-thirdweb-app`, choose either the token or NFT option under nextjs and follow the steps

things to test:
- [ ] it works
- [ ] chooses a project name for you if dont choose
- [ ] node modules are properly installed
- [ ] guide linked after install is easy to follow
- [ ] shows a default option for every contract, and default is shown on top

- [ ] now try cloning the other one using
```
create-thirdweb-app init next-token
```
or
```
create-thirdweb-app init next-nft
```
- [ ] confirm that it asks for a name

then
```
create-thirdweb-app init next-nft xyz
```
- [ ] confirm that it sets up things properly in the `xyz` subdir

- [ ] finally comment thoughts on [product spec](https://www.notion.so/thirdweb/CLI-Game-Plan-c3e36eea80634779a9c303fdabe24356)

need feedback on:
- whether procedure complicated? (shouldnt require a lot of context to understand)
- whether the set up process could be shorter?
- bugs / errors / others

**Comment by joaquim-verges** [comment]
`Contract / Module` shows `react / token / nft`
- should remove module - no more module pls
- react and token/nft are 2 very different things - not sure what to choose here

**Comment by joaquim-verges** [comment]
chose `nft` -> next thing i get `Example? default/next-starter` again i'm not sure what i'm doing 🤔

**Comment by joaquim-verges** [comment]
default name of the app is `tired-pull` ? where does that come from?

**Comment by joaquim-verges** [comment]
ran the nft sample - first thing i clicked is `List all NFTs` - gives me `Please add contract address in the ENV variables` no mention on that at the top of the page? Can we have a simple input with an address?

**Comment by joaquim-verges** [comment]
Feel like send transaction and sign message should not be in the NFT example - pollutes the code and the demo UI

**Comment by saminacodes** [comment]
<img width="682" alt="CleanShot 2022-03-08 at 15 59 30@2x" src="https://user-images.githubusercontent.com/57885104/157346179-172349c7-9165-45ae-a794-eff5eb4cc2c4.png">
Any idea why I am getting this error? Can't run it :(

**Comment by joaquim-verges** [comment]
Would be awesome to have some description for each choice that you can make in the initial setup - to explain what each one is

**Comment by saminacodes** [comment]
![CleanShot 2022-03-08 at 16 09 48@2x](https://user-images.githubusercontent.com/57885104/157347223-3aaf5f15-d092-49c5-8efb-3b2a5442adf0.png)

**Comment by ayshptk** [comment]
@saminacodes are you using a dark mode extension? this is probably because of that

**Comment by saminacodes** [comment]
Not using any extensions afaik but my system is set to dark mode- do you have anything that changes it based off preference?

**Comment by ayshptk** [comment]
damn pretty weird its showing as dark then. have dark mode on mine too but page still comes white, will look into it!
